### ISSUE TITLE
can't get blocks at PU

### ISSUE THREAD

**Issue by aseidl8** [SeedlingsBabylab/idslabel#10]
We have restarted IDSlabel multiple times, but still can't get blocks. Can you help?

**Comment by AnneSWarlaumont** [comment]
Sorry, I had to restart the server so it was down for about a half hour. Andrei is restarting now, so check back in a few minutes and it should be working again. Sorry for the inconvenience.

**Comment by andreiamatuni** [comment]
Should be up and running now

**Comment by aseidl8** [comment]
whoops. poor server! If this happens a lot is there a way you could shoot us an email about it?

**Comment by AnneSWarlaumont** [comment]
Yes, for sure!
