### ISSUE TITLE
executable damaged

### ISSUE THREAD

**Issue by AnneSWarlaumont** [SeedlingsBabylab/idslabel#2]
Hi Andrei &Elika, when I double click the executable I get this message: "idslabel" is damaged and can't be opened. You should move it to the Trash. I am on OS 10.11.5. It does work when I launch it from command line. Thank you for your work on this!

![image](https://cloud.githubusercontent.com/assets/8031754/16063641/7edca5ea-324f-11e6-914b-980d29532520.png)

**Comment by andreiamatuni** [comment]
well that's not good...

I'll look into this
