### ISSUE TITLE
Not playing audio after first block sent

### ISSUE THREAD

**Issue by AnneSWarlaumont** [SeedlingsBabylab/idslabel#3]
Sent the labels for my first block (which went smoothly!), then when I try to play the next block, I can't. Can't play the individual sounds either. (Also my Lab Info isn't showing any activity, just my user name and that's it.) Sorry if this is something in the instructions I missed somehow.

**Comment by andreiamatuni** [comment]
I need to add more to the instructions. Did you double click the next block to load it?

**Comment by AnneSWarlaumont** [comment]
i think i only single clicked it, so maybe that could be the problem. will
try again tomorrow am. i did try requesting more blocks after that and it
sent me more i think without deleting the undone ones. can't remember for
sure though sorry.

thanks!

On Tuesday, June 14, 2016, Andrei Amatuni notifications@github.com wrote:

> I need to add more to the instruction. Did you double click the next block
> to load it?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/SeedlingsBabylab/idslabel/issues/3#issuecomment-226054333,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHqOCuKnarQIF7A4mtfAQtpRTsHHRLtlks5qL0RLgaJpZM4I14XI
> .

## 

Anne S. Warlaumont
Assistant Professor, Cognitive and Information Sciences
University of California, Merced
annewarlaumont.org http://www.annewarlaumont.org
