### ISSUE TITLE
can't get blocks

### ISSUE THREAD

**Issue by aseidl8** [SeedlingsBabylab/idslabel#5]
We used the executable to set up. Everything looks okay, but get blocks does not work (nothing happens).

**Comment by ebergelson** [comment]
can you replicate the issue on multiple machines aand are you:
a) sure you're waiting long enough (can take 15-20s to grab e.g. 3 blocks)
b) that you're using the right i.e. newest config file that andrei sent you yesterday?

**Comment by aseidl8** [comment]
?Yup and yup...

Amanda Seidl, Ph.D.
Professor and Graduate Chair
Dept. of Speech, Language, and Hearing Sciences
Purdue University

**Comment by aseidl8** [comment]
oh, and it won't run on multiple machines because of the version of OS X.

**Comment by andreiamatuni** [comment]
I sent out new versions of the config.json, which should fix some of the issues. Which versions of OS X are you using?
