### ISSUE TITLE
Windows Error with Startup

### ISSUE THREAD

**Issue by babylanguagelab** [SeedlingsBabylab/idslabel#8]
Hello,

We tried setting up the new version of the program and followed the instructions on this page (regarding running the idslabel as a script from the command line). But we seem to be getting errors in the command prompt when we pick the clips directory (as shown in the first photo) and when we try to get blocks (as shown in the second photo). I also included a screenshot of the folder which contains all the files, in case we are missing something. I did put in the newest config file into the folder as well.

![clips directory](https://cloud.githubusercontent.com/assets/11390544/18979419/54accbc0-8690-11e6-938f-1199c083dd25.JPG)
![get blocks](https://cloud.githubusercontent.com/assets/11390544/18979420/54b8db54-8690-11e6-94a1-6f730727ea7c.JPG)
![files in folder](https://cloud.githubusercontent.com/assets/11390544/18979421/54ba8030-8690-11e6-9320-42579e968538.JPG)

**Comment by andreiamatuni** [comment]
When was this tried out? There was a period of time when the server was down after it had been rebooted (like Wednesday afternoon till late Wednesday night). I restarted idsserver and it seems to be working on my end. Before that I was getting the same error you're showing here.

**Comment by babylanguagelab** [comment]
I may have set it up on Wednesday, but I tried it again on Thursday and today, still with no success. I am getting the same error message as before.
